# Dockerfile for mboxMinerva
# -----------------------------------------------------------------------------
# mboxMinerva CI/CD Container - Ruby 3.4.7 (Debian Trixie/Bookworm)
# -----------------------------------------------------------------------------
FROM docker.io/library/ruby:3.4.7-slim
ARG GIT_COMMIT=unknown
ENV GIT_COMMIT=${GIT_COMMIT}

# 1. Install System Dependencies
#    - git: Missing from slim, needed for gemspecs and git-crypt
#    - build-essential: Needed for compiling pg and simhash native extensions
#    - libpq-dev: Needed for pg header files
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    build-essential \
    libpq-dev \
    gnupg \
    libyaml-dev \
    zlib1g-dev \
    libicu-dev \
    && rm -rf /var/lib/apt/lists/*

# 2. Prepare App Directory
WORKDIR /MinervaApp

# 3. Dependency Layer Caching
#    Copy only the dependency manifests first.
#    This ensures 'bundle install' runs only when Gemfile changes, not code.
COPY Gemfile Gemfile.lock ./

# 4. Specify the env var to override the default.
#    At build time this directive doesn't change the default as /usr/local/bundle. But at runtime (which does), this
#    makes Bundler look where the gems actually are located within the container at vendor/bundle.  
ENV BUNDLE_PATH=vendor/bundle

# 5. Install Ruby Dependencies
RUN bundle install

# 6. Runtime Configuration
#    We DO NOT copy source code here (./lib, ./bin).
#    It is bind-mounted at runtime on the gitlab-runner: podman run -v /home/dmr104/ruby_projects/mboxMinerva:/mboxMinerva ...
CMD ["/bin/bash"]
